### ISSUE TITLE
change the primary color

### ISSUE THREAD

**Issue by ajay-prabhakar** [Chromicle/AmritaResource#8]
change the primary color of the app and experiment some colors

**Comment by root-ansh** [comment]
i want to work on this

**Comment by ajay-prabhakar** [comment]
Yeah proceed @root-ansh please provide screenshot also in PR template

**Comment by root-ansh** [comment]
What color do you exactly want, @Chromicle ? Here are some samples:  
![image](https://user-images.githubusercontent.com/31290636/66467646-65800100-eaa2-11e9-876b-dc1565fd62c7.png)

**Comment by ajay-prabhakar** [comment]
Because of we added so many colors it is looking some what weird can you make them into one color

**Comment by root-ansh** [comment]
How about this ?  
![image](https://user-images.githubusercontent.com/31290636/66477699-4b501e00-eab6-11e9-8ec2-24114b301fd1.png)
 I can also change the color of icons if you want, though it will be a slightly bigger change as this will replace those png icons with xmls . It would be good tho, since pngs are very big in size (30-40kb) compare to xmls, which are like, 500 or 600b

**Comment by root-ansh** [comment]
Hey @Chromicle any update on this? should i make  a PR? with IDK ,Red Color?

**Comment by ajay-prabhakar** [comment]
> Hey @Chromicle any update on this? should i make a PR? with IDK ,Red Color?

Use 2 colors may be like using blue as a primary color and other is anything is fine

**Comment by root-ansh** [comment]
How about this mockup?The icons will be white, inside those blue circles
![image](https://user-images.githubusercontent.com/31290636/66718912-d73fae00-ee06-11e9-9789-dfae00be8bd1.png)

**Comment by ajay-prabhakar** [comment]
Yeah cool
